version: 2
jobs:
  build: 
    docker: 
     - image: circleci/python:2.7-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: Git push
          command: |
            sudo apt-get update --fix-missing
            sudo apt-get install -y git
            git config --global user.email "anthony.hw.kong@gmail.com"
            git config --global user.name "Anthony Kong (circleci)"
            git config --global push.default simple
            git tag -a 20180320 -m test
            git push origin 20180320
